# Generated by Django 5.0.6 on 2024-07-08 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_useraccount_preferred_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_type',
        ),
        migrations.CreateModel(
            name='UserTreatmentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_type', models.CharField(choices=[('SOUND_TREATMENT', 'SOUND_TREATMENT'), ('RF_RIGHT', 'RF_RIGHT'), ('RF_LEFT', 'RF_LEFT')], default='SOUND_TREATMENT', max_length=25)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_treatment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
