# Generated by Django 5.0.6 on 2024-07-17 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_medicalrecord_is_deleted_useraccount_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_user', to='users.business'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
