# Generated by Django 5.0.6 on 2024-07-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_address_business_alter_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='prefered_time_zone',
            new_name='preferred_time_zone',
        ),
    ]
