# Generated by Django 5.0.6 on 2024-07-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_language_remove_useraccount_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='preferred_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_users', to='users.language'),
        ),
    ]
