# Generated by Django 5.0.6 on 2024-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_useraccount_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE'), ('BLOCKED', 'BLOCKED'), ('PENDING', 'PENDING')], default='ACTIVE', max_length=50),
        ),
    ]
