# Generated by Django 5.0.6 on 2024-07-29 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_address_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='price_per_unit',
            field=models.FloatField(default=0.0),
        ),
    ]
