# Generated by Django 5.0.6 on 2024-07-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_useraccount_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='tax_document',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AddField(
            model_name='business',
            name='tax_number',
            field=models.BigIntegerField(default=1234567890),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER')], default='MALE', max_length=25),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='prefix',
            field=models.CharField(default='Mr.', max_length=5),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('CLINIC', 'CLINIC'), ('RESELLER', 'RESELLER'), ('INDIVIDUAL', 'INDIVIDUAL')], default='INDIVIDUAL', max_length=25),
        ),
        migrations.AlterField(
            model_name='business',
            name='organization_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
