# Generated by Django 5.0.6 on 2024-07-29 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_business_tax_document_business_tax_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
