# Generated by Django 5.0.6 on 2024-08-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_useraccount_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tax_number',
            field=models.CharField(max_length=100),
        ),
    ]
