# Generated by Django 5.0.6 on 2024-08-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_business_tax_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='preferred_time_zone',
            field=models.CharField(blank=True, default='CDT', max_length=25, null=True),
        ),
    ]
