# Generated by Django 5.0.6 on 2024-08-02 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_useraccount_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='preferred_language',
        ),
        migrations.CreateModel(
            name='UserLaguageMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_users', to='users.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'language')},
            },
        ),
    ]
