# Generated by Django 5.0.6 on 2024-08-07 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0002_alter_currencyvaluemapping_euro_equivalent_value_and_more'),
        ('users', '0026_useraccount_reseller_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='price_mapping',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_mapping_user', to='core_utils.currencyvaluemapping'),
        ),
        migrations.AlterField(
            model_name='contactnumber',
            name='number',
            field=models.BigIntegerField(),
        ),
    ]
