# Generated by Django 5.0.6 on 2024-08-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_remove_useraccount_price_per_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='price_mapping',
            new_name='price_per_unit',
        ),
    ]
