# Generated by Django 5.0.6 on 2024-08-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyvaluemapping',
            name='euro_equivalent_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='currencyvaluemapping',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
