# Generated by Django 5.0.6 on 2024-08-08 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0002_alter_currencyvaluemapping_euro_equivalent_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('asked_question', models.CharField(choices=[('BEFORE_SESSION', 'BEFORE_SESSION'), ('AFTER_SESSION', 'AFTER_SESSION')], max_length=30)),
                ('question_type', models.CharField(choices=[('QUESTION', 'QUESTION'), ('FEEDBACK', 'FEEDBACK')], max_length=30)),
                ('question_reoccurrence_time', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='category_images')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notch_percentage', models.FloatField()),
                ('notch_db', models.BigIntegerField()),
                ('session_done_percentage', models.FloatField()),
                ('sound_therapy', models.IntegerField()),
                ('pause_duration', models.FloatField()),
                ('too_hot_pause', models.FloatField()),
                ('rf_session_day', models.IntegerField()),
                ('rf_session_length', models.IntegerField()),
                ('pause_limit', models.IntegerField()),
                ('power_changing_time', models.IntegerField()),
                ('hear_tinnitus', models.IntegerField()),
                ('frequency_test_diffrence', models.IntegerField()),
                ('beep_time', models.FloatField()),
                ('reseller_product_price', models.FloatField()),
                ('patient_product_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MusicFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='music_files')),
                ('music_length', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='music_category', to='core_utils.musiccategory')),
            ],
        ),
    ]
