# Generated by Django 5.0.6 on 2024-08-08 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0003_feedback_musiccategory_settings_musicfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='musiccategory',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='settings',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
