# Generated by Django 5.0.6 on 2024-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_utils', '0004_alter_feedback_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='beep_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='frequency_test_diffrence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='hear_tinnitus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='notch_db',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='notch_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='patient_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pause_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='pause_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='power_changing_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='reseller_product_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rf_session_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rf_session_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='session_done_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sound_therapy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='too_hot_pause',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
